### ISSUE TITLE
Unable to establish new websocket

### ISSUE THREAD

**Issue by RingoHHuang** [MLHale/gazepoint-websockets#10]
Hi @MLHale - 

I've started the server and it's listening for connections. I'm now trying to create client-side web socket.

I'm running the code provided in the Basic Manual Testing section, and am encountering this error message: `VM409:1 WebSocket connection to 'ws://gazepoint/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`.

It seems that `window.location.host` returns an empty string. Does this need to be defined somehow?

I'm testing this in a Google Chrome console, the Gazepoint Control application is turned on (although I'm not sure if that's necessary), and the server is running. Also, treat me as someone who has never used javascript before.

**Comment by MLHale** [comment]
Hi @RingoHHuang

Probably if you used this command in a new tab it is because you have not first visited localhost. I never thought about that situation - so this is helpful. I will update the instructions accordingly.

You should type ```localhost``` in your address bar, then open the terminal.

Alternatively, you could just replace ```window.location.host``` with ```localhost``` or your ip address.

The reason I have ```window.location.host``` in the instructions is that my assumption is that eyestream is ran alongside another web application (typically the application that would be consuming the eyetracker data from eyestream). In that case the domain (e.g. myapp.com) would be resolved as window.location.host and eyestream (running as a websocket) would be invoked by ```ws://myapp.com/gazepoint/```.

**Comment by MLHale** [comment]
Ok @RingoHHuang - clarification made - your feedback was really helpful here. It didn't occur to me before.

**Comment by RingoHHuang** [comment]
Thanks for updating the instructions, @MLHale. They look much clearer!

I am having trouble connecting to `localhost` from my browsers (I've tried both Chrome and Firefox). I get `ERR_CONNECTION_REFUSED` when typing localhost in the address bar, and `Content Security Policy: The page’s settings blocked the loading of a resource at ws://localhost/gazepoint/ (“connect-src”).
` when trying to run the code through the console after swapping the address with localhost. 

It seems like I need to somehow whitelist `localhost` from my browser's Content Security Policy, but I have yet to find a solution after diving through various forums related to this issue. I'll do some more digging, but I thought I'd ask in case you knew of a quick solution or of an alternative way to test your code.

**Comment by MLHale** [comment]
Try visiting ```localhost:8888``` in the browser address bar, then running ```ws://localhost:8888/gazepoint/``` in the console.

Usually the window.location.host would extract the needed port too.

**Comment by RingoHHuang** [comment]
Thanks @MLHale - That does the trick. It looks like I'm only able to connect if the port number is also specified. 

I've just tested everything with my Gazepoint 60 Hz eye-tracker and everything runs as expected.

**Comment by MLHale** [comment]
@RingoHHuang Perfect! Thanks for testing that. I just added the port number to the instructions in the example for running locally without integration into an app.

Your review here to make the instructions more clear has been really helpful.

**Comment by RingoHHuang** [comment]
Thanks and no problem!
